// this file (Program.cs) was automatically generated by command "dotnet new mvc -n GitBrowser"
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using GitBrowser.Services; // Added

namespace YourNamespace
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.
            builder.Services.Configure<GitSettings>(builder.Configuration.GetSection("GitSettings")); // Added
            builder.Services.AddScoped<IGitService, GitService>(); // Added
            builder.Services.AddControllersWithViews();
			// this enables the automatic compilation of cshtml-files
			// to see the automatic compilation om the commandline following line was added to appsettings.json
			// "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation": "Debug"	 
            builder.Services.AddControllersWithViews().AddRazorRuntimeCompilation();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthorization();

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Git}/{action=Index}");

            app.Run();
        }
    }
}
